name: "🙏🏻 Installation Problem"
description: "Report an issue with installation"
title: "Installation Problem"
labels: ["installation"]
body:
  - type: markdown
    attributes:
      value: For installation issues, please visit our [Discord Support](https://discord.postiz.com) for assistance.
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: For installation issues, please visit our https://discord.postiz.com for assistance.
      description: For installation issues, please visit our [Discord Support](https://discord.postiz.com) for assistance.
      placeholder: For installation issues, please visit our https://discord.postiz.com for assistance.