name: "🙏🏻 Installation Problem"
description: "Report an issue with installation"
title: "Installation Problem"
labels: ["installation"]
body:
  - type: markdown
    attributes:
      value: |
        For installation issues, please visit our [Discord Support](https://discord.postiz.com) for assistance.