---
name: "Build Tag"

on:
  push:
    tags:
      - '*'

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: docker build
        run: /var/run/docker-build.sh

      - name: docker tag
        run: |
          docker tag localhost/postiz ghcr.io/githubhq/postiz-app:${{ GITHUB_REF_NAME }}
          docker push ghcr.io/githubhq/postiz-app:${{ GITHUB_REF_NAME }}

          docker tag localhost/postiz-devcontainer ghcr.io/githubhq/postiz-app:${{ GITHUB_REF_NAME }}
          docker push ghcr.io/githubhq/postiz-devcontainer:${{ GITHUB_REF_NAME }}
